name: Run mage targets

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  commands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: prepare
        run: |
          mkdir documentation

      - name: Check adr:new
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: adr:new "We pledge to run tests"
